--  Create Users Table
CREATE TABLE IF NOT EXISTS DATASOURCE(NAME VARCHAR(50) NOT NULL PRIMARY KEY,MAXACTCONN INTEGER NOT NULL,DRIVERCLASS VARCHAR(50) NOT NULL,IDLECONN INTEGER NOT NULL,USERNAME VARCHAR(50) NULL,PASSWORD VARCHAR(150) NULL,URL VARCHAR(512) NOT NULL,QUERY VARCHAR(100) NULL,WAIT INTEGER NOT NULL);
--  Create Granted Authorities Table
CREATE TABLE IF NOT EXISTS `GRANTED_AUTHORITIES` (
`USERNAME` varchar(50) collate latin1_general_ci NOT NULL,
`AUTHORITY` varchar(50) collate latin1_general_ci NOT NULL,
KEY `FK_GRANTED_AUTHORITIES_USERS` (`USERNAME`),
KEY `FK_GRANTED_AUTHORITIES_AUTHORITIES` (`AUTHORITY`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
--  Create Authorities Table
CREATE TABLE IF NOT EXISTS `AUTHORITIES` (
`AUTHORITY` varchar(50) collate latin1_general_ci NOT NULL,
`DESCRIPTION` varchar(100) collate latin1_general_ci default NULL,
PRIMARY KEY (`AUTHORITY`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
--  Create Users Table
CREATE TABLE IF NOT EXISTS `USERS` (
`USERNAME` varchar(50) collate latin1_general_ci NOT NULL,
`PASSWORD` varchar(50) collate latin1_general_ci NOT NULL,
`ENABLED` tinyint(1) NOT NULL,
`DESCRIPTION` varchar(100) collate latin1_general_ci default NULL,
PRIMARY KEY (`USERNAME`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

CREATE TABLE IF NOT EXISTS `CONTENTLOCATION` (
`CONTENTID` varchar(100) NOT NULL,
`REVISION` int(11) NOT NULL,
`NAME` varchar(200) NOT NULL,
`SOLNID` varchar(100) NOT NULL,
`DESCRIPTION` varchar(200) NOT NULL,
`DIRPATH` varchar(767) NOT NULL,
PRIMARY KEY (`CONTENTID`),
UNIQUE KEY `DIRPATH` (`DIRPATH`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `CONTENTITEM` (
`CONTITEMID` varchar(100) NOT NULL,
`REVISION` int(11) NOT NULL,
`NAME` varchar(200) NOT NULL,
`parent_id` varchar(100) DEFAULT NULL,
`PATH` varchar(767) NOT NULL,
`TITLE` varchar(200) NOT NULL,
`MIMETYPE` varchar(100) DEFAULT NULL,
`URL` varchar(254) DEFAULT NULL,
`LATESTVERNUM` int(11) DEFAULT NULL,
`EXTENSION` varchar(10) NOT NULL,
`WRITEMODE` int(11) NOT NULL,
PRIMARY KEY (`CONTITEMID`),
UNIQUE KEY `PATH` (`PATH`),
KEY `FK692B5EEC44F32395` (`parent_id`),
CONSTRAINT `FK692B5EEC44F32395` FOREIGN KEY (`parent_id`) REFERENCES `CONTENTLOCATION` (`CONTENTID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
