INSERT INTO `AUTHORITIES` VALUES ('Admin','Super User') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('Anonymous','User has not logged in') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('Authenticated','User has logged in') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('ceo','Chief Executive Officer') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('cto','Chief Technology Officer') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('dev','Developer') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('devmgr','Development Manager') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
INSERT INTO `AUTHORITIES` VALUES ('is','Information Services') ON DUPLICATE KEY UPDATE DESCRIPTION = DESCRIPTION;
